##################################################################################
#         Configuration
##################################################################################
env:
  DEPLOYMENT_NAME: ${{vars.DEPLOYMENT_NAME}}
  APP_CODE_BRANCH: ${{vars.APP_CODE_BRANCH}}
  PARENT_DEPLOYMENT_REPO: ${{vars.PARENT_DEPLOYMENT_REPO}}
  PARENT_DEPLOYMENT_NAME: ${{vars.PARENT_DEPLOYMENT_NAME}}
  PARENT_DEPLOYMENT_BRANCH: ${{vars.PARENT_DEPLOYMENT_BRANCH}}
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
  FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}

##################################################################################
#         Main Code
##################################################################################
name: Sync Google Sheets Content 
on:
  workflow_dispatch:
    inputs:
      pr-title:
        description: Title for PR
        type: string
        default: sync content from google sheets
      pr-body:
        description: Description for PR
        type: string
        default: Automated PR creation from actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: initialize repository
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.PAT }}
          fetch-depth: 0 

      - name: Check out app code
        uses: actions/checkout@v3
        with:
          repository: "IDEMSInternational/parenting-app-ui.git"
          ref: ${{env.APP_CODE_BRANCH}}

      - name: Checkout parent repo if needed
        if: env.PARENT_DEPLOYMENT_REPO != ''
        uses: actions/checkout@v3
        with:
          path: ".idems_app/deployments/${{env.PARENT_DEPLOYMENT_NAME}}"
          repository: ${{env.PARENT_DEPLOYMENT_REPO}}
          ref: ${{env.PARENT_DEPLOYMENT_BRANCH}}

      - name: Checkout deployment
        uses: actions/checkout@v3
        with:
          path: ".idems_app/deployments/${{env.DEPLOYMENT_NAME}}"
      - name: Populate Encryption key
        if: env.DEPLOYMENT_PRIVATE_KEY != ''
        run: echo "${{env.DEPLOYMENT_PRIVATE_KEY}}" > ./.idems_app/deployments/${{env.DEPLOYMENT_NAME}}/encrypted/private.key

        # TODO - populate firebase as part of deployment set
      - name: Populate Firebase Config
        if: env.FIREBASE_CONFIG != ''
        run: echo 'export const firebaseConfig = ${{env.FIREBASE_CONFIG}}' > src/environments/firebaseConfig.ts
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-yarn-v1-

      - name: Install node modules
        run: yarn install

      - name: Set deployment
        run: yarn workflow deployment set $DEPLOYMENT_NAME

      - name: Sync content
        run: yarn workflow sync

      - name: Move assets over
        run: |
          cp -R .idems_app/deployments/${{env.DEPLOYMENT_NAME}}/app_data/ app_data/

      - name: Move sheets over
        run: |
          cp -R  /home/runner/work/plh-facilitator-app-zm-content/plh-facilitator-app-zm-content/.idems_app/deployments/${{env.DEPLOYMENT_NAME}}/app_data/sheets app_data/sheets  
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app_data/assets/ app_data/sheets/
          git commit -m "Automated commit message"

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""
          destination_branch: "main"
          pr_title: ${{ inputs.pr-title }}
          pr_body: ${{ inputs.pr-body }}
          github_token: ${{ secrets.PAT }}
